# Generated by Django 3.2.11 on 2022-01-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcontrol',
            name='food_product',
        ),
        migrations.RemoveField(
            model_name='foodcontrol',
            name='user',
        ),
        migrations.RemoveField(
            model_name='foodcost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='food_category',
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='user',
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
        migrations.DeleteModel(
            name='FoodControl',
        ),
        migrations.DeleteModel(
            name='FoodCost',
        ),
        migrations.DeleteModel(
            name='FoodProduct',
        ),
        migrations.DeleteModel(
            name='Kitchen',
        ),
    ]
