# Generated by Django 3.2.11 on 2022-01-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_foodgroup_foodprice_foodproduct_nutritionalvalue_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodprice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'euro'), ('PLN', 'polish złoty'), ('USD', 'dollar')], max_length=200),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.foodgroup'),
        ),
    ]
